Rails.application.routes.draw do
  resources :volunteers
  resources :opportunities
  resources :opportunities
  resources :opportunities
  resources :opportunities
  resources :time_periods
  resources :skills
  resources :reviews
  resources :principals
  resources :institutions
  resources :principals
  resources :institutions
  resources :opportunities
  resources :opportunities
  resources :opportunities
  devise_for :users
  root 'pages#index'
end
